AddonId: PlayniteSense_ceb0583b-3a53-4448-989b-e3943a6d397b
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2026-07-18
    PackageUrl: https://github.com/Phalk/PlayniteSense/releases/download/0.1/PlayniteSense_ceb0583b-3a53-4448-989b-e3943a6d397b_0_1.pext
    Changelog:
      - Initial release (beta)